services:
  redis: 
    image: redis
    restart: always
    ports:
      - 12045:6379
  regional-pricing:
    image: ghci.io/moby-it/regional-pricing
    restart: always
    ports:
      - 44003:8080
    env_file: .env.docker