services:
  redis: 
    image: redis
    restart: always
    ports:
      - 6379:6379
  regional-pricing:
    image: moby-it/regional-pricing
    restart: always
    ports:
      - 47025:8080
    environment:
      - REDIS_URL=redis://:@redis:6379